// Code generated by protoc-gen-go. DO NOT EDIT.
// source: post.proto

package timeline

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PostI struct {
	User                 string   `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	Stamp                uint64   `protobuf:"varint,4,opt,name=stamp" json:"stamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostI) Reset()         { *m = PostI{} }
func (m *PostI) String() string { return proto.CompactTextString(m) }
func (*PostI) ProtoMessage()    {}
func (*PostI) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_04a5dc24da7386e5, []int{0}
}
func (m *PostI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostI.Unmarshal(m, b)
}
func (m *PostI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostI.Marshal(b, m, deterministic)
}
func (dst *PostI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostI.Merge(dst, src)
}
func (m *PostI) XXX_Size() int {
	return xxx_messageInfo_PostI.Size(m)
}
func (m *PostI) XXX_DiscardUnknown() {
	xxx_messageInfo_PostI.DiscardUnknown(m)
}

var xxx_messageInfo_PostI proto.InternalMessageInfo

func (m *PostI) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *PostI) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *PostI) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *PostI) GetStamp() uint64 {
	if m != nil {
		return m.Stamp
	}
	return 0
}

func init() {
	proto.RegisterType((*PostI)(nil), "pt.um.sdle.timeline.PostI")
}

func init() { proto.RegisterFile("post.proto", fileDescriptor_post_04a5dc24da7386e5) }

var fileDescriptor_post_04a5dc24da7386e5 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xc8, 0x2f, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2e, 0x28, 0xd1, 0x2b, 0xcd, 0xd5, 0x2b, 0x4e,
	0xc9, 0x49, 0xd5, 0x2b, 0xc9, 0xcc, 0x4d, 0xcd, 0xc9, 0xcc, 0x4b, 0x55, 0x0a, 0xe7, 0x62, 0x0d,
	0xc8, 0x2f, 0x2e, 0xf1, 0x14, 0x12, 0xe2, 0x62, 0x29, 0x2d, 0x4e, 0x2d, 0x92, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x41, 0x62, 0x25, 0xa9, 0x15, 0x25, 0x12, 0x4c, 0x10, 0x31, 0x10,
	0x5b, 0x48, 0x80, 0x8b, 0xb9, 0xb4, 0x28, 0x47, 0x82, 0x19, 0x2c, 0x04, 0x62, 0x0a, 0x89, 0x70,
	0xb1, 0x16, 0x97, 0x24, 0xe6, 0x16, 0x48, 0xb0, 0x28, 0x30, 0x6a, 0xb0, 0x04, 0x41, 0x38, 0x4e,
	0x5c, 0x51, 0x1c, 0x30, 0x4b, 0x92, 0xd8, 0xc0, 0x0e, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x88, 0x92, 0x45, 0xaa, 0x8e, 0x00, 0x00, 0x00,
}
