// Code generated by protoc-gen-go. DO NOT EDIT.
// source: timeline.proto

package timeline

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TimelineI struct {
	Id                   uint32                           `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	FeedMap              map[string]*TimelineI_PostStream `protobuf:"bytes,3,rep,name=feedMap" json:"feedMap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PostHistory          *TimelineI_PostStream            `protobuf:"bytes,4,opt,name=postHistory" json:"postHistory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *TimelineI) Reset()         { *m = TimelineI{} }
func (m *TimelineI) String() string { return proto.CompactTextString(m) }
func (*TimelineI) ProtoMessage()    {}
func (*TimelineI) Descriptor() ([]byte, []int) {
	return fileDescriptor_timeline_bbeb191b33c5af99, []int{0}
}
func (m *TimelineI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimelineI.Unmarshal(m, b)
}
func (m *TimelineI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimelineI.Marshal(b, m, deterministic)
}
func (dst *TimelineI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimelineI.Merge(dst, src)
}
func (m *TimelineI) XXX_Size() int {
	return xxx_messageInfo_TimelineI.Size(m)
}
func (m *TimelineI) XXX_DiscardUnknown() {
	xxx_messageInfo_TimelineI.DiscardUnknown(m)
}

var xxx_messageInfo_TimelineI proto.InternalMessageInfo

func (m *TimelineI) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TimelineI) GetFeedMap() map[string]*TimelineI_PostStream {
	if m != nil {
		return m.FeedMap
	}
	return nil
}

func (m *TimelineI) GetPostHistory() *TimelineI_PostStream {
	if m != nil {
		return m.PostHistory
	}
	return nil
}

type TimelineI_PostStream struct {
	Posts                []*PostI `protobuf:"bytes,2,rep,name=posts" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimelineI_PostStream) Reset()         { *m = TimelineI_PostStream{} }
func (m *TimelineI_PostStream) String() string { return proto.CompactTextString(m) }
func (*TimelineI_PostStream) ProtoMessage()    {}
func (*TimelineI_PostStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_timeline_bbeb191b33c5af99, []int{0, 0}
}
func (m *TimelineI_PostStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimelineI_PostStream.Unmarshal(m, b)
}
func (m *TimelineI_PostStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimelineI_PostStream.Marshal(b, m, deterministic)
}
func (dst *TimelineI_PostStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimelineI_PostStream.Merge(dst, src)
}
func (m *TimelineI_PostStream) XXX_Size() int {
	return xxx_messageInfo_TimelineI_PostStream.Size(m)
}
func (m *TimelineI_PostStream) XXX_DiscardUnknown() {
	xxx_messageInfo_TimelineI_PostStream.DiscardUnknown(m)
}

var xxx_messageInfo_TimelineI_PostStream proto.InternalMessageInfo

func (m *TimelineI_PostStream) GetPosts() []*PostI {
	if m != nil {
		return m.Posts
	}
	return nil
}

func init() {
	proto.RegisterType((*TimelineI)(nil), "pt.um.sdle.timeline.TimelineI")
	proto.RegisterMapType((map[string]*TimelineI_PostStream)(nil), "pt.um.sdle.timeline.TimelineI.FeedMapEntry")
	proto.RegisterType((*TimelineI_PostStream)(nil), "pt.um.sdle.timeline.TimelineI.PostStream")
}

func init() { proto.RegisterFile("timeline.proto", fileDescriptor_timeline_bbeb191b33c5af99) }

var fileDescriptor_timeline_bbeb191b33c5af99 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xc9, 0xcc, 0x4d,
	0xcd, 0xc9, 0xcc, 0x4b, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2e, 0x28, 0xd1, 0x2b,
	0xcd, 0xd5, 0x2b, 0x4e, 0xc9, 0x49, 0xd5, 0x83, 0x49, 0x49, 0x71, 0x15, 0xe4, 0x17, 0x97, 0x40,
	0x14, 0x28, 0x5d, 0x63, 0xe2, 0xe2, 0x0c, 0x81, 0x4a, 0x78, 0x0a, 0xf1, 0x71, 0x31, 0x65, 0xa6,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x06, 0x31, 0x65, 0xa6, 0x08, 0xb9, 0x72, 0xb1, 0xa7, 0xa5,
	0xa6, 0xa6, 0xf8, 0x26, 0x16, 0x48, 0x30, 0x2b, 0x30, 0x6b, 0x70, 0x1b, 0x69, 0xeb, 0x61, 0x31,
	0x50, 0x0f, 0x6e, 0x80, 0x9e, 0x1b, 0x44, 0xb5, 0x6b, 0x5e, 0x49, 0x51, 0x65, 0x10, 0x4c, 0xaf,
	0x90, 0x37, 0x17, 0x37, 0xc8, 0x4a, 0x8f, 0xcc, 0xe2, 0x92, 0xfc, 0xa2, 0x4a, 0x09, 0x16, 0x05,
	0x46, 0x0d, 0x6e, 0x23, 0x4d, 0x02, 0x46, 0x05, 0xe4, 0x17, 0x97, 0x04, 0x97, 0x14, 0xa5, 0x26,
	0xe6, 0x06, 0x21, 0xeb, 0x96, 0xb2, 0xe3, 0xe2, 0x42, 0x48, 0x09, 0x19, 0x70, 0xb1, 0x82, 0x24,
	0x8b, 0x25, 0x98, 0xc0, 0xee, 0x93, 0xc2, 0x6a, 0x28, 0x48, 0xbd, 0x67, 0x10, 0x44, 0xa1, 0x54,
	0x2a, 0x17, 0x0f, 0xb2, 0x2b, 0x85, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0xc1, 0x9e, 0xe6, 0x0c,
	0x02, 0x31, 0x85, 0xec, 0xb9, 0x58, 0xcb, 0x12, 0x73, 0x4a, 0x53, 0x25, 0x98, 0x48, 0x75, 0x28,
	0x44, 0x9f, 0x15, 0x93, 0x05, 0xa3, 0x13, 0x57, 0x14, 0x07, 0x4c, 0x6d, 0x12, 0x1b, 0x38, 0xac,
	0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x32, 0xd5, 0xce, 0x02, 0x9e, 0x01, 0x00, 0x00,
}
